package io.github.fontysvenlo.ais.persistence;

import io.github.fontysvenlo.ais.persistence.api.CustomerRepository;
import java.time.LocalDate;
import java.util.List;
import javax.sql.DataSource;

import io.github.fontysvenlo.ais.datarecords.CustomerData;

/**
 * This class knows everything about storing and retrieving customers from the database.
 * At the moment only returns dummy object with an id that is set.
 * Normally it will connect to a database and do all the handling.
 */
class CustomerRepositoryImpl implements CustomerRepository {
    private DataSource db;

    public CustomerRepositoryImpl(DBConfig config) {
        this.db = DBProvider.getDataSource(config);
    }

    /**
     * @see CustomerRepository#add(CustomerData)
     */
    @Override
    public CustomerData add(CustomerData customerData) {
        // Create dummy customerData object with id. Normally, the id would be generated by the database
        return new CustomerData( 1, customerData.firstName(), customerData.lastName(), customerData.dateOfBirth());
    }

    /**
     * @see CustomerRepository#getAll()
     */
    @Override
    public List<CustomerData> getAll() {
        // TODO: Implement the actual database storage
        // For now, return a dummy list
        return List.of(new CustomerData(1, "John", "Doe", LocalDate.of(2025, 1, 1)));
    }
}
