name: Verification workflow

on:
  # TODO: integrate the 'restapi' branch
  push:
    branches: [ "restapi*", "main" ]
  pull_request:
    branches: [ "restapi*", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Maven verify
      run: mvn -B verify
